### ISSUE TITLE
Open source license? 

### ISSUE THREAD

**Issue by taimoorgit** [Hatzen/LibOQSTestApp#11]
Dear Hatzen, I was wondering if you have a plan for setting up a license (MIT/GPL/etc.) for this project. 

Thanks!

**Comment by Hatzen** [comment]
Thanks for your advice.  
  
The license part is a bit tricky as i copied some code from the official liboqs-java project.  

https://github.com/Hatzen/LibOQSTestApp/tree/master/liboqs-android/jni/jni from https://github.com/open-quantum-safe/liboqs-java/tree/master/src/main/c  
https://github.com/Hatzen/LibOQSTestApp/tree/master/liboqs-android/src/main/java/com/example/liboqs from 
https://github.com/open-quantum-safe/liboqs-java/tree/master/src/main/java/org/openquantumsafe  

-----
I just added a LICENSE file, this project is licensed under the MIT. But to me it is not really important to state the License and copyright notice.  
BUT as i copied the sources we have to state the License and copyright of then official project https://github.com/open-quantum-safe/liboqs-java/blob/master/LICENSE
